title: Beautiful Barpak
email: btfulnepal@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Beautiful Barpak is a website that shows the beauty of Barpak village.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://barpak.org
asset_base_url: /assets

google_analytics: # your google analytics id

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
